runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /robots\.txt
  static_files: public/robots.txt
  upload: public/robots\.txt
- url: /favicon\.ico
  static_files: public/img/icon.png
  upload: public/img/icon\.png
- url: /img
  static_dir: public/img
- url: /css
  static_dir: public/css
- url: /js
  static_dir: public/js
- url: /data
  static_dir: public/data

- url: /dcdata
  static_dir: public/dcdata

- url: /.*
  script: controller.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
