application: aaaharu-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
- url: /favicon\.ico
  static_files: img/icon.png
  upload: img/icon\.png
- url: /img
  static_dir: img
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /data
  static_dir: data

- url: /dcdata
  static_dir: dcdata

- url: /.*
  script: controller.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
